### ISSUE TITLE
Biomarker Portal (next 2 months)

### ISSUE THREAD

**Issue by DaniallMasood** [clinical-biomarkers/biomarker-issue-repo#10]
- Change Color of portal from blue to muted purple
- Put Biomarker KG app on front end
- point to biomarkerkb.org
- small changes to portal (remove GlyGen logo picture on front page, remove GW and UG logos at the bottom of the page)

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni can you estimate time for 1,3, and 4? for biomarker KG i will set up a meeting with us and Erol to understand what needs to be done

**Comment by DaniallMasood** [comment]
- [x] Remove background image on biomarker home page and replace with a section of this image
![Screenshot 2024-09-27 at 11 59 11 AM](https://github.com/user-attachments/assets/83849941-ddbc-41b0-9178-c85c9519e4d3)

(taken from Adobe Firefly and allowed for use as per https://www.adobe.com/products/firefly.html#questions-we-have-answers)

- [x] remove GWU and UGA logos in footer and on "Our Mission" Page

Color change to teal (#008080) in:

- [x] Header and Footer for every page
- [x] Our Mission Page - where "Our Mission is written"
- [x] In "how to Cite" on left hand bar "Relevant Papers"
- [x] Remove "Test Website" from the top


- [x] Biomarker KG app (pointed to from front end)
(decide on how to incorporate it fully later)
https://bkg.dev.maayanlab.cloud/
This can go under the explore header. IN THE FOOTER IT CAN BE CALLED "Biomarker Knowledge Graph"

Pointing from biomarkerkb.org will be done after 9/20

- [x] change from Biomarker BETA to Biomarker KB
- [x] Remove Test Website tag in top left corner

@sujeetvkulkarni

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood Our Mission Page - where "Our Mission is written"
this is an image if you want I can add an image there or just set the background color to teal. If you want image, please share it.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni just set to teal that works for us

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood I have done above changes, please verify.
https://glygen.ccrc.uga.edu/frontend/

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni looks great! thank you

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni sorry just ran into some additional changes that can be made.

on Results page when we get the table, can the table headers also be changed to teal and the "reset filters" and "modify search" buttons can also be changed to teal

"FeedBack" banner as well needs to be teal

thank you

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood So all buttons/download options in teal color? Also go through search pages check buttons tab headers there too.  Look into icon when the page is loading - currently its GlyGen logo. 
I will work on theses changes and upload changes as and when done but might take some time.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni yes all buttons and download options should be teal. On search page as well make the search button teal and the headers as well. "Biomarker Search" should be teal and te tabs below can have teal text.

Can we make the loading icon just the regular circling dots? We dont have a logo per say that we could replicate the GlyGen Loading icon

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood I was able to do above changes and some more. They are available for testing -
https://glygen.ccrc.uga.edu/frontend/. 
If you think more changes are required then list them on this ticket. I will work on them after some time.
But mostly I think all major places are now covered.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni just one more small change and that is to put "Biomarker" and "KB" together in one single word. Wherever it appears. Thanks

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni on the home page we can change "Biomarker Partnership Project" to "BiomarkerKB Project"

**Comment by sujeetvkulkarni** [comment]
@seankim658 
https://glygen.ccrc.uga.edu/frontend/biomarker-list/a38fbe90c7bcee791e9a8a247641e97a
this shows 2.4 though. Will it work on https://dev.biomarkerkb.org/ once routing is stopped?

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood Done, please check.

**Comment by DaniallMasood** [comment]
thanks @sujeetvkulkarni
