### ISSUE TITLE
Clean up Markerdb Data 

### ISSUE THREAD

**Issue by seankim658** [clinical-biomarkers/biomarker-issue-repo#11]
Markerdb's license (they might've changed it?) allows for us to use their data and push it into the API, etc. It is slightly mis-formatted right now. Needs to be cleaned up slightly before we can push it per the email thread with Darren (Subject: reasoned OWL file).

**Comment by DaniallMasood** [comment]
sent to sean. review and close ticket if it looks fine

**Comment by seankim658** [comment]
Fixed in data push on 9-26-24.
