### ISSUE TITLE
Biomarker Wiki Page for BiomarkerKB

### ISSUE THREAD

**Issue by DaniallMasood** [clinical-biomarkers/biomarker-issue-repo#16]
No rush on this. Make biomarker wiki page that will include all information on biomarkerKB, documentation, and FAQ
Model after glygen and bco wiki pages

**Comment by DaniallMasood** [comment]
at some point after we receive the final letter to start work

**Comment by seankim658** [comment]
Won't be doing this until we have our VMs setup (ticket [here](https://github.com/clinical-biomarkers/biomarker-issue-repo/issues/18)).

**Comment by seankim658** [comment]
Dacian responded to me, we're going to setup a call next week to work on getting this setup.

**Comment by seankim658** [comment]
This is done. Wiki is at https://wiki.biomarkerkb.org
