### ISSUE TITLE
Request biomarkerkb VMs

### ISSUE THREAD

**Issue by seankim658** [clinical-biomarkers/biomarker-issue-repo#18]
Going to request Dacian sets up our biomarkerkb VMs and then I will migrate our backend infrastructure there from the hivelab VMs. Raja mentioned we want to setup dev, beta, and prod VMs and drop tst, although I should discuss with Rene first.

@ReneRanzinger Do you want the front end to move to the eventual biomarkerkb VMs? And do you have any preference on Raja's suggestion for the tst VM? He mentioned you were in favor of keeping it.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni uses containers, so moving the it to another server is no issue. We have to think about who is deploying changes. For GlyGen Sujeet can do it on the tst server but Robel has to do the production deployment. If you want to have a test AND production server its up to you. Currently we only have a "production" version.

**Comment by seankim658** [comment]
Is Robel doing the production deployment just the GlyGen convention or does Sujeet not have access to the production server? Or something else? 

I think I'll also request the tst VM to recreate the backend testing environment workflow that biomarker has now but I know eventually Raja wants to just use dev, beta, and prod.

**Comment by ReneRanzinger** [comment]
As far as I remember Sujeet only has access to tst. Dev is Robels playground. And deployment to beta and production is done by Robel.

**Comment by seankim658** [comment]
Ah got it, I'll discuss with Raja, update this ticket, and then send Dacian an email to get everything up.

**Comment by seankim658** [comment]
Had a quick call with Dacian, he is going to setup the three VMs for biomarker: prd, dev, beta. These should be up by end of day tomorrow. Once the VMs are set up, I'm going to start migrating the backend over. Before the VM can be exposed to the public web the GW security team has to complete a security assessment on the site. Dacian mentioned the turnaround time for the GW security team isn't the best so I'm going to try and get everything up and running on the VMs as quick as possible so we can initiate that process.

Also discussed with Raja, we think Sujeet should handle the frontend deployment if that works with you guys. He will get access all the VMs.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni see above.

**Comment by seankim658** [comment]
@sujeetvkulkarni  As far as handling the minimum needed to get the security assessment going, we just need to setup the dev server. Dacian said he will give the security team explicit instructions that the dev server should be the only one assessed since the prd setup will just be a mirror of the dev server.

**Comment by sujeetvkulkarni** [comment]
@seankim658 I am fine with this and can deploy it on the severs which I have access to.

**Comment by seankim658** [comment]
@sujeetvkulkarni @DaniallMasood The prd and dev VMs have been setup by Dacian. Please email him your public keys at rtshelp@gwu.edu so he can add them to the server. He'll then send you a temporary access code for your first time ssh'ing in and then you'll setup your 2fa code for future logins.

**Comment by sujeetvkulkarni** [comment]
@seankim658 sent an email to Dacian with public key.

**Comment by seankim658** [comment]
@sujeetvkulkarni Thanks. I'm in the process of migrating the API and database over today and want to get that done hopefully by end of today. Once that and the frontend is up, I can reach out to Dacian to initiate the security assessment so we can be ready for the CFDE meeting.

**Comment by seankim658** [comment]
@sujeetvkulkarni the backend is all setup on the dev server. Let me know when the frontend is deployed. Also, the biomarkers with negative scores are also in the data on the dev server so that can be tested as well.

**Comment by seankim658** [comment]
I believe Dacian scheduled the security assessment for Tuesday so we need to be ready by then in order to make sure we can then setup and deploy the production site for all hands after the assessment is completed.

**Comment by seankim658** [comment]
Right now the dev API root url is dev.biomarkerkb.org/api

**Comment by seankim658** [comment]
@sujeetvkulkarni Let me know if you have any issues getting setup on the dev server. We will need to be setup for the security assessment so we will be on track for CFDE all hands. I confirmed with suejeet you are in the docker group on the server. If any system dependencies on the server need to be installed let me know.

**Comment by seankim658** [comment]
@sujeetvkulkarni I just had a call with Dacian and we updated to follow the same URL convention as GlyGen. So the dev api is now at api.dev.biomarkerkb.org and the data page link is data.dev.biomarkerkb.org. The prod links will similarly be at api.biomarkerkb.org and data.biomarkerkb.org. 

For now I left the apache routing in for dev.biomarkerkb.org/api so the current deployment doesn't break but next time you deploy could you update these. Thanks again, we're just about finished up. Once we have this done we'll just deploy on prod and we'll be good to go for CFDE all hands next week. Thanks!

**Comment by sujeetvkulkarni** [comment]
@seankim658 Sure, I will update the api url. Also share me the prod vm name.

**Comment by seankim658** [comment]
biomarkerkb-vm-prd.biochemistry.gwu.edu

I already had Dacian increase the partition size for the rl-var partition so we are good to go there. I'll start working on the apache config, in your email you mentioned the prod container is on port 7070 so I'll route it there. Let me know if you run into any other issues.

**Comment by sujeetvkulkarni** [comment]
@seankim658 Looks like both vm names point to the same VM?

**Comment by seankim658** [comment]
@sujeetvkulkarni what do you mean? Each vm (prd, beta, dev) has some shared partitions to reduce the amount of redundancy. The home and data/shared partitions are shared across the vms if that was what you were looking at.

**Comment by sujeetvkulkarni** [comment]
@seankim658 glygen-biomarker-prod container up and running on port 9090 as 7070 was in use. So use 9090 port in Apache for prod.
