### ISSUE TITLE
Portal Down

### ISSUE THREAD

**Issue by seankim658** [clinical-biomarkers/biomarker-issue-repo#22]
Hey Sujeet, noticed the portal is down. Wasn't sure if you were currently working on it or if something went wrong. Let me know if theres anything you need from my end, thanks.

**Comment by sujeetvkulkarni** [comment]
@seankim658 nothing from your side. Server is down, sorry for the inconvenience.

**Comment by seankim658** [comment]
Closing, Sujeet sent an email that the issue is resolved now and the server is back up.
