### ISSUE TITLE
Biomarkers with Negative Score

### ISSUE THREAD

**Issue by DaniallMasood** [clinical-biomarkers/biomarker-issue-repo#25]
Biomarkers with negative score should be marked and denoted with a red banner on the biomarker entry page.

@sujeetvkulkarni what is the best way to do this?

**Comment by sujeetvkulkarni** [comment]
@seankim658 is negative value important? Can you make them all from 0 and above by adding a weight or something?

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni yes negative score is important for us. Not all biomarker entries are viewed and are given -1. Some entries are not complete biomarkers and are given -2 score. 0 score is assigned to biomarkers for generic conditions (eg, "cancer")

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood oh ok got it. We can highlight it on list page in some way, either we can highlight link to biomarker page or score value as red or something. Based on your preference.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni i think highlighting score value would be great. is it possible to also highlight the "Biomarker Details for XXXXXX" red on the biomarker entry page as well?

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood If you can add the score value in details page api. We can do it.

**Comment by DaniallMasood** [comment]
@seankim658 can you do this? -1 for all ClinVar and -2 for SenNet?

**Comment by seankim658** [comment]
The scores are already on the details API response under the key `score`. Technically on the list endpoint on the backend I just rename the key from `score` to `hit_score` before returning the response because originally we needed the API response to match the GlyGen list response as close as possible. However, in the database it is stored as `score` since our concept of a score isnt exactly a hit score like GlyGen's score concept is. I'm not sure if we also want to rename the search results page column to just `score` but Daniall can decide on that. 

Right now we do not have the negative scored biomarkers in the database yet, they will get pushed in the next data push.

**Comment by seankim658** [comment]
But everything on the backend is in place to implement this. From what I understood when Raja explained it, should just check the score less than 0 and then just have a small red banner with some text on the detail page. @DaniallMasood can provide the text. And then I'm not sure how you want to format the search results page whether that should have anything for the negative scores.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni @seankim658 yeah we can do a red banner on the top right of the biomarker entry page and the text can be "Pending Review"

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood we can do this change but I think it will be best if we do this when data is available, so we can test it. Just let me know on this ticket when the data is pushed.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni that is fine

@seankim658 will the data be pushed tomorrow with the negative scores?

**Comment by seankim658** [comment]
The data with negative scores is pushed on the dev biomarkerkb server. Not going to push on the hivelab server since plan is to have the hivelab server backend deprecated by end of this week.

**Comment by sujeetvkulkarni** [comment]
@seankim658 Can you share biomarker ids with negative score.

**Comment by seankim658** [comment]
AC1966-3
AB0396-1

These both have a score of -1. Let me know if you need anymore.

**Comment by sujeetvkulkarni** [comment]
@seankim658 @DaniallMasood Done, please check. 
@seankim658 Also, need to fix hit score values in the tooltip (on the list page) so that tooltip also shows negative values.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni sorry I am not seeing any change on AC1966-3? Could it be because it is not being shown as a negative value on the list page when I search?
![image](https://github.com/user-attachments/assets/70a8a4a5-f025-48b2-92fe-7f36ca223ca0)

**Comment by seankim658** [comment]
@DaniallMasood Are you on dev.biomarkerkb.org? That's where we're updating, not the UGA site

**Comment by DaniallMasood** [comment]
i see let me check there. I am assuming now all changes will be done on dev? @seankim658

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood Change is there on  dev.biomarkerkb.org maybe in your case browser is catching the old routing. Use different browser if needed.

![Screenshot 2024-10-17 at 3 01 49 PM](https://github.com/user-attachments/assets/7f802707-12d5-4622-a39f-3cf362d78404)

![Screenshot 2024-10-17 at 3 01 27 PM](https://github.com/user-attachments/assets/a06ef766-a01e-4a88-b130-e5732b7b6bae)

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni can you change the text to "Pending Review" thanks

**Comment by sujeetvkulkarni** [comment]
@DaniallMasood Done.

**Comment by DaniallMasood** [comment]
@sujeetvkulkarni thank you
