### ISSUE TITLE
Production Container

### ISSUE THREAD

**Issue by seankim658** [clinical-biomarkers/biomarker-issue-repo#39]
Hey Sujeet, 

Could you change [this](https://github.com/clinical-biomarkers/biomarker-frontend/blob/0f33ae23d2234d64c841d58ab15f920f69d8049e/docker-compose.biom-prod.yml#L10) line to be `https://biomarkerkb.org` and re-build/start the container on prod? 

I'm not 100% sure but I think that is causing the frontend to attempt to pull the static files from the incorrect URL. Dev just has `https://dev.biomarkerkb.org` and that works fine so I suspect this might be the issue. Dev console below for prod:

![image](https://github.com/user-attachments/assets/ea18b404-585b-4be5-a421-613e17c1ebb5)

**Comment by sujeetvkulkarni** [comment]
@seankim658 this property is not for container but for internal use. So this is not issue. container should be available at http://localhost:9090 to the Apache server in the VM.

**Comment by sujeetvkulkarni** [comment]
Can you use 9090 port in Apache and route https://biomarkerkb.org that way? Then I will be able to check if something is wrong.

**Comment by seankim658** [comment]
Got it, everything works. Only thing is the data tile still goes here: https://hivelab.biochemistry.gwu.edu/biomarker-partnership/data instead of here: https://data.biomarkerkb.org/.

**Comment by seankim658** [comment]
![image](https://github.com/user-attachments/assets/33181921-66fd-4523-b74d-6342f0820ea4)

Just noticed that the top level evidence section doesn't seem to be populating.

**Comment by sujeetvkulkarni** [comment]
@seankim658 which link, id? can you add details.

**Comment by seankim658** [comment]
As far as I can tell happens for all records. Every biomarker page I've looked at has this issue.

**Comment by seankim658** [comment]
Raja is presenting today at CFDE all hands so I wouldn't push any changes to production today. Can push to dev but should probably avoid production downtime as people will be browsing the site throughout the day.

**Comment by sujeetvkulkarni** [comment]
@seankim658 ok, production still points to ccrc url right?

**Comment by sujeetvkulkarni** [comment]
> ![image](https://private-user-images.githubusercontent.com/33474168/378844785-33181921-66fd-4523-b74d-6342f0820ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDc3MzYsIm5iZiI6MTcyOTYwNzQzNiwicGF0aCI6Ii8zMzQ3NDE2OC8zNzg4NDQ3ODUtMzMxODE5MjEtNjZmZC00NTIzLWI3NGQtNjM0MmYwODIwZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0MzAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNjEyMzljOTk2NTVhMTlmMjBkOWMwNDBiOGYwMThmNmI2YWNmOGY3Y2E5NDBlNmRmNDdmNzQzMmMyMGVkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1g1TWVeE72FY-csmuhRO3jdVTvD3WzhHXDgcLYIKN9A)
> 
> Just noticed that the top level evidence section doesn't seem to be populating.

For cross reference and exposure agent data in api response is empty.
For evidence section like discussed earlier if evidence_list:[] in evidence_source:[] is empty we dont show data in that section. So either you can add an empty string evidence_list:[] or maybe we need to change the logic in which we display data.

**Comment by seankim658** [comment]
Cross reference and exposure agent is fine, right now we dont have that data. And re: evidence ok I remember that now. 

And production now points to the production container. The security assessment passed last night so its now publicly open and you dont have to be on VPN anymore to see the prod site.

**Comment by sujeetvkulkarni** [comment]
@seankim658 when Raja will be demoing today? Can I update prod container, I have fixed dev container with data link, added empty string evidence_list:[] etc. If you think there is time for demo I can quickly update prod container.

**Comment by seankim658** [comment]
Sorry we got busy with different things at CFDE yesterday didn't see this. But you can push today if you have time. We're not presenting today.

**Comment by seankim658** [comment]
@sujeetvkulkarni Raja is asking if we are tracking using google analytics. I'm not sure if we are/what that would entail. Are we?

**Comment by sujeetvkulkarni** [comment]
@seankim658 we are not using google analytics now but we can use glygen google analytics key immediately to track http://biomarkerkb.org/ usage.

**Comment by sujeetvkulkarni** [comment]
@seankim658 I have updated prod container and fixed data, faq links issue.
Also, made changes to start using glygen google analytics key to track biomarker prod usage.

**Comment by seankim658** [comment]
@sujeetvkulkarni Thank you! I'm not familiar with google analytics, is it fine for us to use the same key as glygen? Swathi, the new hire who is responsible for the glygen google analytics stuff will also be doing the biomarkerkb google analytics tracking. Is that easier for her to track everything in one place? I'm assuming the GA data indicates which site each data point corresponds to?
