### ISSUE TITLE
Portal Blank Page

### ISSUE THREAD

**Issue by seankim658** [clinical-biomarkers/biomarker-issue-repo#40]
When I visit https://biomarkerkb.org the portal seems to load fine and then it disappears and I get a blank white page. 

In the console I see a `TypeError`. Not sure if this is related?  

![image](https://github.com/user-attachments/assets/e857b71f-500d-4d08-8079-d8cf67e3ee74)

Unrelated but the home page also seems to hit the logging API with these query string params: 

```
{"id":"","user":"Undecided","type":"error","page":"home","message":"Network error. home_init api call. Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"}
```

But the `home_init` call works properly and gets a 200 return code?

**Comment by sujeetvkulkarni** [comment]
@seankim658 Did you made some changes in home_init api response, if so can you revert those changes.

**Comment by seankim658** [comment]
Before the home_init call from the frontend was failing due to the endpoint route (it was at `/pages/detail/home_init`). All I did was correct the route so that the home_init endpoint was correctly at `/pages/home_init` so the home_init call is successful. I just reverted that change so the call now fails again when loading the portal and I don't get the white screen issue anymore. 

The home_init endpoint returns some stats on our data that Raja eventually wants on the home page.

**Comment by sujeetvkulkarni** [comment]
@seankim658 Do not directly modify prod apis, otherwise there is a chance that it might break the portal - as all existing apis expect a response in particular way. Use dev/test environment to test your changes and once working then push to prod.
