### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by seankim658** [clinical-biomarkers/biomarker-issue-repo#41]
Sent an email with the GTag for the biomarkerkb project. Just opening this ticket for tracking purposes. Will close when we're set up.

**Comment by seankim658** [comment]
@sujeetvkulkarni Is all that is needed to make this change just swapping out the GTag key [here on line 12](https://github.com/clinical-biomarkers/biomarker-frontend/blob/a2033184d95b407fe85a7b6c92c904c6eca7f1f6/src/App.js#L12) and then running `docker compose up -d --build` to re-build/deploy the container? Let me know if I'm missing anything else that's needed to make this change, otherwise I can just go ahead and do this.

**Comment by sujeetvkulkarni** [comment]
@seankim658 I have updated the GA key and redeployed the container, please verify if traffic is directed to new key.

**Comment by seankim658** [comment]
@sujeetvkulkarni Thanks, looks like its working.
