### ISSUE TITLE
Search Examples

### ISSUE THREAD

**Issue by seankim658** [clinical-biomarkers/biomarker-issue-repo#44]
From Raja: 

Change the examples on the biomarker search page from `AN6278-1, Colorectal Cancer` to `AN6278, AN6278-5, Colorectal Cancer`.

**Comment by sujeetvkulkarni** [comment]
@seankim658 I have made the changes on Simple and Advanced search.
https://dev.biomarkerkb.org/biomarker-search/
Please check.

**Comment by seankim658** [comment]
Thanks, closing.
