### ISSUE TITLE
Add BiomarkerKB logo to Wiki page

### ISSUE THREAD

**Issue by jeet-vora** [clinical-biomarkers/biomarker-issue-repo#80]
Please Add BiomarkerKB logo to Biomarker Wiki homepage. The logo may change in the future

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/5bdc8c58-8150-48a6-a49e-375d3b578ced" />

<img width="237" alt="image" src="https://github.com/user-attachments/assets/3d53964a-d182-468a-9fce-47bd6a30b7dd" />

**Comment by seankim658** [comment]
I will try, but that picture has very horizontal dimensions so I don't think it'll look very good. It will either be very small since I'll have to shrink it down so the horizontal axis can fit there or if I don't resize I imagine it'll be cut off on the sides.

**Comment by seankim658** [comment]
@jeet-vora  I had to resize it in order for it to fit and not get cutoff on the left and right. It will definitely look better when we have a more square-ish traditional logo image.

**Comment by jeet-vora** [comment]
@seankim658 the logo looks blurred. Can you look into it. What can be done to make it high resolution?
